language: node_js
node_js:
  - "8"
script:
  - echo "Deploy!!"
branches:
  only: 
    - master
install:
  - |
    if [ $TRAVIS_EVENT_TYPE != "push" || $TRAVIS_BRANCH != "master" ]; then
      travis_terminate 0;
    fi
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
after_success:
  - |
    if [ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" ]; then
      firebase deploy --project thoughtcache --token $FIREBASE_TOKEN;
    fi