language: node_js
node_js:
  - "8"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
after_success:
  - firebase deploy --project thoughtcache --token $FIREBASE_TOKEN